
default: &default 
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: 5

development:
  <<: *default
  database: file_upload
  username: root
  password: 

test:
  <<: *default

production:
  <<: *default
 
