# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f000705907ba2a92d41f88fe2af9459e874efd17af10bd015b4bf5f1cd319479747fe583a14bae24a99af13ad02c575ce15503269fbaa2fa60d6164d5bda29c5

test:
  secret_key_base: 3847704ebd13e4278abbc9d672512acfce627a47701b57af1d9135a3374a01f4de86a22c8b129d634c67632fd0743ea5c9dae00d298452dc09d2806ef797e55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
